// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU6R6sCyskHcELT-Q_TTmG32oqw5J4Ats',
    appId: '1:93296071638:web:2ce0589f9d0a8976b90a77',
    messagingSenderId: '93296071638',
    projectId: 'kjlhlhk',
    authDomain: 'kjlhlhk.firebaseapp.com',
    storageBucket: 'kjlhlhk.appspot.com',
    measurementId: 'G-ETYRTWKH6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofoHgu0Nh0iIJwv6IUe6z9rh8sCV5roM',
    appId: '1:93296071638:android:d4acf43ad21af9b8b90a77',
    messagingSenderId: '93296071638',
    projectId: 'kjlhlhk',
    storageBucket: 'kjlhlhk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvzh-soN_l7arY_chQJeLHGo6ZRfmkRfQ',
    appId: '1:93296071638:ios:b5cffa1c9ede1daab90a77',
    messagingSenderId: '93296071638',
    projectId: 'kjlhlhk',
    storageBucket: 'kjlhlhk.appspot.com',
    iosClientId: '93296071638-l3luq4o8fk9p3ik4refb43lmvc8k6821.apps.googleusercontent.com',
    iosBundleId: 'com.example.products',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvzh-soN_l7arY_chQJeLHGo6ZRfmkRfQ',
    appId: '1:93296071638:ios:d67571fcaeb010afb90a77',
    messagingSenderId: '93296071638',
    projectId: 'kjlhlhk',
    storageBucket: 'kjlhlhk.appspot.com',
    iosClientId: '93296071638-rdgbs78t54f3lro6eimhuf3jo9o0mo2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.products.RunnerTests',
  );
}
